<<<<<<< HEAD
---
pagetitle: Description of Data
---

## Description of Data

As mentioned in the [Introduction](./), to answer our main, our strategy was to develop different analysis to answer smaller questions.
  
### Remodeling of existing and construction of new buildings   
  
Before any construction project begins in New York City, an application must be submitted for review by the Department of Buildings to make sure that the plans are in compliance with Building Code. The majority of construction requires a Department of Buildings permit.
  
The data we were able to get, shows the details for every building permit filed with the Department of Buildings, available for download from [The NYC Open Data portal](https://data.cityofnewyork.us/Housing-Development/DOB-Permit-Issuance/ipu4-2q9a "NYC Open Data portal").

This dataset is a list of building permits filed for a particular day and associated data, from 1990 to date. It contains building permits for both new buildings and alterations / remodeling.
  
A Data Dictionary containing field codes and descriptions of the data set can be found [here](https://data.cityofnewyork.us/api/views/ipu4-2q9a/files/87608d5b-1986-4a21-a8a5-7a38e65f9993?download=true&filename=DD_DOB_Permit_Issuance_2018-03-07.xlsx "Data Dictionary for building permits").
    
      
### Real State Sales
_Describe 1) how the data was collected, 2) how you accessed it, and 3) any other noteworthy features_
    
    
### Property Market Values

We got the market values dataset from The Department of Finance (DOF), which every year estimates the property's market value for all New York City properties, comparing each property market value with recent sales in the neighborhood. The estimated market value is used by the DOF to determine the assessed value and then the City's property tax rates are applied to the assessed value to calculate the property taxes for the next tax year.
  
The data can be accessed and downloaded directly from [the DOF's website here](http://www1.nyc.gov/site/finance/taxes/property-assessments.page "Data for Property Market Values")
     
There, we were able to find the tentative property assessment for fiscal year 2019 (with a total NYC property Market Value of about $1.258 trillion, an increase of $108.4 billion, or 9.4 percent from the 2018 Fiscal Year), as well as the final property assessments from 2018 fiscal year, back to 2009 fiscal year, **one dataset for each year**.
   
a Data Dictionary containing field codes and descriptions of the data sets can be accessed [here](http://www1.nyc.gov/assets/finance/downloads/tar/tarfieldcodes.pdf "Data Dictionary for property market values").

The data consists of Access databases so we used RODBC library to read the databases using "odbcConnectAccess('my_Access_Database_to_read.mdb')". 
   
   
### Property Assessed Values
   
Since our analysis of Property Market Values resulted inconclusive to answer our question and the publicly available data offered by the DOF for Market Values goes back to 2007 only, while news about the project and properties in the area of influence becoming more valued, date many years back, as additional work, since we wanted to analyse years previous to the commencement of the construction of phase 1, we performed an additional research and were able to find property "Assessed Values" back to 2003 in the "Primary Land Use Tax Lot Output" (PLUTO) dataset, developed by the New York City Department of City Planning's (DCP) Information Technology Division (ITD), which is New York City's primary land use agency. 

Although the property "Assessed Values" are different from property "Market Values", we found that they are linearly correlated since, [according to the NY state DOF](https://www.tax.ny.gov/pit/property/learn/howassess.htm) "source of info"), the property "Assessed Value" is a percentage of the estimated "Market Value" of a property depending of the tax class so, as example, in a city or town assessing at 100% of market value for a specific tax class, the market value for that class is equal to the assessment value.

The PLUTO datasets that we used are an extensive land use and geographic data at the tax lot level, containing more than seventy fields derived from data maintained by different city agencies.

The data can be accessed and downloaded directly from [the DCP's website here](http://www1.nyc.gov/site/planning/data-maps/open-data/bytes-archive.page?sorts[year]=0 "Data for Property Assessed Values")
  
There, we were able to find the property assessed values from 2017 year, back to 2003, one dataset for every year (15 different datasets in total).

a Data Dictionary containing field codes and descriptions of the data sets can be accessed [here](http://www1.nyc.gov/assets/planning/download/pdf/data-maps/open-data/pluto_datadictionary.pdf "Data Dictionary for property assessed values").

The datasets are shapefiles so we used the "foreign" library to read the data files of the shapefiles using "read.dbf('my_shapefile_to_read.dbf')". 
  
  
### Other Datasets?
  
_Describe 1) how the data was collected, 2) how you accessed it, and 3) any other noteworthy features_

  
  
=======
---
pagetitle: Description of Data
---

## Description of Data

As mentioned in the [Introduction](./), to answer our main, our strategy was to develop different analysis to answer smaller questions.
  
### Remodeling of existing and construction of new buildings   
  
Before any construction project begins in New York City, an application must be submitted for review by the Department of Buildings to make sure that the plans are in compliance with Building Code. The majority of construction requires a Department of Buildings permit.
  
The data we were able to get, shows the details for every building permit filed with the Department of Buildings, available for download from [The NYC Open Data portal](https://data.cityofnewyork.us/Housing-Development/DOB-Permit-Issuance/ipu4-2q9a "NYC Open Data portal").

This dataset is a list of building permits filed for a particular day and associated data, from 1990 to date. It contains building permits for both new buildings and alterations / remodeling.
  
A Data Dictionary containing field codes and descriptions of the data set can be found [here](https://data.cityofnewyork.us/api/views/ipu4-2q9a/files/87608d5b-1986-4a21-a8a5-7a38e65f9993?download=true&filename=DD_DOB_Permit_Issuance_2018-03-07.xlsx "Data Dictionary for building permits").
    
      
### Real State Sales
_Describe 1) how the data was collected, 2) how you accessed it, and 3) any other noteworthy features_
    
    
### Property Market Values

We got the market values dataset from The Department of Finance (DOF), which every year estimates the property's market value for all New York City properties, comparing each property market value with recent sales in the neighborhood. The estimated market value is used by the DOF to determine the assessed value and then the City's property tax rates are applied to the assessed value to calculate the property taxes for the next tax year.
  
The data can be accessed and downloaded directly from [the DOF's website here](http://www1.nyc.gov/site/finance/taxes/property-assessments.page "Data for Property Market Values")
     
There, we were able to find the tentative property assessment for fiscal year 2019 (with a total NYC property Market Value of about $1.258 trillion, an increase of $108.4 billion, or 9.4 percent from the 2018 Fiscal Year), as well as the final property assessments from 2018 fiscal year, back to 2009 fiscal year, **one dataset for each year**.
   
a Data Dictionary containing field codes and descriptions of the data sets can be accessed [here](http://www1.nyc.gov/assets/finance/downloads/tar/tarfieldcodes.pdf "Data Dictionary for property market values").

The data consists of Access databases so we used RODBC library to read the databases using "odbcConnectAccess('my_Access_Database_to_read.mdb')". 
   
   
### Property Assessed Values
   
Since our analysis of Property Market Values resulted inconclusive to answer our question and the publicly available data offered by the DOF for Market Values goes back to 2007 only, while news about the project and properties in the area of influence becoming more valued, date many years back, as additional work, since we wanted to analyse years previous to the commencement of the construction of phase 1, we performed an additional research and were able to find property "Assessed Values" back to 2003 in the "Primary Land Use Tax Lot Output" (PLUTO) dataset, developed by the New York City Department of City Planning's (DCP) Information Technology Division (ITD), which is New York City's primary land use agency. 

Although the property "Assessed Values" are different from property "Market Values", we found that they are linearly correlated since, [according to the NY state DOF](https://www.tax.ny.gov/pit/property/learn/howassess.htm) "source of info"), the property "Assessed Value" is a percentage of the estimated "Market Value" of a property depending of the tax class so, as example, in a city or town assessing at 100% of market value for a specific tax class, the market value for that class is equal to the assessment value.

The PLUTO datasets that we used are an extensive land use and geographic data at the tax lot level, containing more than seventy fields derived from data maintained by different city agencies.

The data can be accessed and downloaded directly from [the DCP's website here](http://www1.nyc.gov/site/planning/data-maps/open-data/bytes-archive.page?sorts[year]=0 "Data for Property Assessed Values")
  
There, we were able to find the property assessed values from 2017 year, back to 2003, one dataset for every year (15 different datasets in total).

a Data Dictionary containing field codes and descriptions of the data sets can be accessed [here](http://www1.nyc.gov/assets/planning/download/pdf/data-maps/open-data/pluto_datadictionary.pdf "Data Dictionary for property assessed values").

The datasets are shapefiles so we used the "foreign" library to read the data files of the shapefiles using "read.dbf('my_shapefile_to_read.dbf')". 
  
  
### Other Datasets?
  
_Describe 1) how the data was collected, 2) how you accessed it, and 3) any other noteworthy features_

  
  
>>>>>>> 525efa3d7f67f0580900f6e4f6b641b9872c405c
<br>